Function  ISEDCOMPRESSCONTENT
EndFunc
Function ISEDSAVETOFILE 
EndFunc
Function ISEDREMOVEDOCUMENT 
EndFunc
Function ISEDSETINFORMATION 
EndFunc
Function ISEDPERMISSIONS 
EndFunc
Function ISEDENCRYPT 
EndFunc
Function ISEDUNLOCKKEY 
EndFunc
Function ISEDNEWDOCUMENT 
EndFunc
Function ISEDSETORIGIN 
EndFunc
Function ISEDSETMEASUREMENTUNITS 
EndFunc
Function ISEDSETPAGEDIMENSIONS 
EndFunc
Function ISEDCOMPRESSIMAGES 
EndFunc
Function ISEDNEWPAGE 
EndFunc
Function ISEDADDIMAGEFROMFILE 
EndFunc
Function ISEDDRAWIMAGE 
EndFunc
Function ISEDDRAWTEXT
EndFunc
Function ISEDLASTERRORCODE
EndFunc
Function ISEDADDTRUETYPEFONT 
EndFunc
Function ISEDSELECTFONT 
EndFunc
Function ISEDSETTEXTSIZE 
EndFunc
Function ISEDSETTEXTUNDERLINE 
EndFunc
Function ISEDSETTEXTCOLOR 
EndFunc
Function ISEDSETTEXTALIGN 
EndFunc
Function ISEDDRAWWRAPPEDTEXT 
EndFunc
Function ISEDFITTEXTBOX 
EndFunc
Function ISEDSETFILLCOLOR 
EndFunc
Function ISEDSETLINECOLOR 
EndFunc
Function ISEDSETLINEWIDTH 
EndFunc
Function ISEDDRAWBOX 
EndFunc
Function ISEDDRAWROUNDEDBOX 
EndFunc
Function ISEDDRAWLINE 
EndFunc
Function ISEDDRAWSCALEDIMAGE 
EndFunc
Function ISEDCOMPRESSFONTS 
EndFunc
Function ISEDGETTEXTWIDTH
EndFunc 
Function ISEDGETTEXTHEIGHT
EndFunc